# Generated by Django 2.1.4 on 2018-12-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventaris',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.CharField(error_messages={'unique': 'A student with that nim already exists.'}, max_length=255, unique=True)),
                ('nama_barang', models.CharField(max_length=255)),
                ('jumlah', models.IntegerField(default=1)),
                ('kondisi_barang', models.CharField(choices=[('baik', 'Baik'), ('sedang', 'Sedang'), ('rusak', 'Rusak')], default='baik', max_length=20)),
            ],
        ),
    ]
